code review
htmlacademy-javascript/1089259-keksobooking-21 pull request #2
Opened 2020-09-27 10:11 UTC by ekaterina-s

2020-09-27 21:51 UTC, kosovych requested changes

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +const generatedhotels = [];
используй camelCase

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +      avatar: `img/avatars/user02.png`,
не используй шаблонные строки если внутри нет переменных

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +      features: ["wifi", "dishwasher", "parking", "washer", "elevator", "conditioner"],
должен быть массив случайных строк, а не захардкоженых

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +console.log(generatedhotels);
удаляй console.log перед отправкой

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +  generateHotels();
ф-ция generateHotels возвращает значение, здесь она вернула его вникуда, этот вызов по сути ничего не делает

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +console.log(template);
все переменные объявляются в начале файла

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +  generatedhotels.push(generateHotels());
вынеси в отлельную функцию

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +      x: Math.floor(Math.random() * 630) + 230,
в ТЗ имеется ввиду, что число ограничено шириной  блока с картой

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +      x: Math.floor(Math.random() * 630) + 230,
если числа можно откуда-то получить, то их нужно подучить, например ширину можно взять с DOM

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +for (let i = 0; i < 8; i++) {
8 - магическое число, должно приходить с аргументов функции

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +      x: Math.floor(Math.random() * 630) + 230,
230? откуда это число?

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +  domElement.style.left = location.x + 570;
у тебя все pin с одинаковыми координатами:
1. Сейчас в функции location это undefined, нужно использовать object.location
2. Не хватает единиц измерения

2020-09-27 21:51 UTC, kosovych commented on js/main.js
> +  domElement.style.top = location.y + 375;
![image](https://user-images.githubusercontent.com/19348382/94376682-b4480000-0124-11eb-93d3-f8a994150631.png)

2020-09-27 21:55 UTC, kosovych requested changes

2020-09-27 21:55 UTC, kosovych commented on js/main.js
> +      ],
массив строк случайной длины, содержащий адреса фотографий, а у тебя всегда один и тот же

2020-09-27 21:55 UTC, kosovych commented on js/main.js
> +      type: `flat`,
так же случайными образом определяй

2020-09-27 21:55 UTC, kosovych commented on js/main.js
> +      address: "600, 350",
должно соврадать с location

2020-09-28 20:53 UTC, ekaterina-s commented on js/main.js
> +      type: `flat`,
ты имеешь ввиду type?

2020-10-01 16:24 UTC, kosovych requested changes

2020-10-01 16:24 UTC, kosovych commented on js/main.js
> +  l.length = Math.floor(Math.random() * array.length) + 0;
что дает  `+ 0`?

2020-10-01 16:24 UTC, kosovych commented on js/main.js
> +        y: Math.floor(Math.random() * 630) + 130
и что за число 130?

2020-10-01 16:24 UTC, kosovych commented on js/main.js
> +      y: Math.floor(Math.random() * 630) + 130
смотри выше

2020-10-01 16:24 UTC, kosovych commented on js/main.js
> +    createdFragment.appendChild(renderDomElements(array[i]));
renderDomElements - не корректное название,  ДОМ элементы бывают разные, а ты генеришь конкретные

2020-10-01 16:24 UTC, kosovych commented on js/main.js
> +const addRenderedDomElementsToTheCode = (createdFragment, array, space) => {
addRenderedDomElementsToTheCode - не корректное название, ДОМ элементы бывают разные, а ты генеришь конкретные, ToTheCode - лишнее

2020-10-01 16:24 UTC, kosovych commented on js/main.js
> +  domElement.querySelector('.map__pin').alt = object.offer.title;
проверь в инспекторе правильно ли ты задаешь картинку

2020-10-01 16:24 UTC, kosovych commented on js/main.js
> +  domElement.querySelector('.map__pin').style.top = object.location.y + mapPinYPosittion + 'px';
`object.location.x + mapPinXPosittion + 'px'` - перепеши через шаблонную строку

2020-10-01 16:24 UTC, kosovych commented on js/main.js
> +const MAP_PIN_FROM_TOP = 400;
откуда эти числа?

2020-10-01 16:24 UTC, kosovych commented on js/main.js
> +const checkInOuts = ['12:00', '13:00', '14:00'];
это константы, они известны с самого начала выполнения программы, поэтому нужно прописными записать

2020-10-01 16:24 UTC, kosovych commented on js/main.js
> +const MAP_PIN_HEIGHT = mapPin.height;
а это просто переменные, которые мы вычисляем по ходу выполнения программы

2020-10-01 16:26 UTC, kosovych requested changes

2020-10-01 16:26 UTC, kosovych commented on js/main.js
> +'use strict';
так же нужно запустить команду `npm run test` и исправить все ошибки

2020-10-01 17:19 UTC, ekaterina-s commented on js/main.js
> +        y: Math.floor(Math.random() * 630) + 130
http://joxi.ru/J2bdbXYtVgxyEr 130 дано по условию

2020-10-01 17:51 UTC, ekaterina-s commented on js/main.js
> +const MAP_PIN_FROM_TOP = 400;
из html кода

2020-10-03 17:59 UTC, merged