Module7 task1
htmlacademy-javascript/1089259-keksobooking-21 pull request #8
Opened 2020-10-24 20:52 UTC by ekaterina-s

2020-10-25 11:25 UTC, kosovych requested changes

2020-10-25 11:25 UTC, kosovych commented on js/main.js
> +    turnOnActiveMode();
зачем по изменению фильтра переводить страницу в активное состояние? согласно ТЗ только по нажатию на `.map__pin--main` страница переводится в активное состояние

2020-10-25 11:25 UTC, kosovych commented on js/load.js
> +    load: load
имена методов не должны совпадать с пространством имен. предлагаю назвать модуль data, а метод get

2020-10-25 11:25 UTC, kosovych commented on js/filter.js
> +  const fragment = document.createDocumentFragment();
фрагмент это не пременная и не константа. фрагмент должен создаваться там, где он нужен. нет нужны постоянно его хванить в памяти

2020-10-25 11:25 UTC, kosovych commented on js/filter.js
> +  const filterHotels = (type, array) => {
array - плохое название для переменной, оно долна быть понятным, а не столь абстрактным

2020-10-25 11:25 UTC, kosovych commented on js/filter.js
> +    } else {
избавься от ветки else

2020-10-25 11:25 UTC, kosovych commented on js/filter.js
> +'use strict';
посмотри в Network, у тебя каждый раз при изменении фильтра запрашиваются новые данные с сервера, данные приходят одни и те же. я бы записал их один раз и во время фильтрации использовал бы записанные

2020-10-25 12:43 UTC, ekaterina-s commented on js/load.js
> +    load: load
:)

2020-10-25 12:50 UTC, ekaterina-s commented on js/filter.js
> +  const fragment = document.createDocumentFragment();
:)

2020-10-25 13:06 UTC, ekaterina-s commented on js/filter.js
> +  const filterHotels = (type, array) => {
:)

2020-10-26 21:58 UTC, kosovych commented on js/load.js
> +    load: load
![image](https://user-images.githubusercontent.com/19348382/97233009-ebbed080-17e6-11eb-958c-25b5e9674550.png)
не исправленно (было load load load, а стало data data data)
+ используй короткую запись свойств

2020-10-26 21:59 UTC, kosovych commented on js/filter.js
> +'use strict';
не исправленно

2020-10-26 22:00 UTC, kosovych requested changes

2020-10-26 22:00 UTC, kosovych commented on js/filter.js
> +        return hotel.offer.type === type;
избавься от ветки else

2020-10-26 22:01 UTC, kosovych commented on js/filter.js
> +'use strict';
https://www.loom.com/share/48e70fbf4ea74475b1de9d56ad7aed20

2020-10-27 18:44 UTC, merged